### ISSUE TITLE
A potential issue with the upd.Trade function in fectp.q

### ISSUE THREAD

**Issue by wbcpeter3000** [itfin/Tx#15]
Based on "CTP客户端开发指南V3.5-中文":
>  在综合交易平台和交易所中，每笔报单都有 3 组唯一序列号，保证其与其他报单是不重复的。
> 1. FrontID + SessionID + OrderRef
> 2. ExchangeID + TraderID + OrderLocalID
> 3. _**ExchangeID + OrderSysID**_

Should a small part of .upd.Trade in fectp.q change from 
```
if[null .db[.ctrl.O;z;`sym];z:exec first id from .db[.ctrl.O] where ordid=w];
```
to 
```
if[null .db[.ctrl.O;z;`sym];z:exec first id from .db[.ctrl.O] where ordid=w,ex=`$y`ExchangeID];
```
So add ```,exex=`$y`ExchangeID``` in the where clause

**Comment by itfin** [comment]
已更新过滤条件为`ordid=w,,(fs2e each sym)=.enum.ctptexmap `$y`ExchangeID
