### ISSUE TITLE
wlog type error on ftbt .z.wc

### ISSUE THREAD

**Issue by oirontro** [itfin/Tx#4]
https://github.com/itfin/Tx/blob/450c2438e68f172822b65c0e6fdce096a755bb51/core/base.q#L79

`.db.LOG` 的 `logtime` 是 `timestamp` 类型。 `core/base.q` 中的 `now[]` 也返回
`timestamp`.  但是， `feed/backtest/ftbacktest.q` 中的 `now[]` 返回的是 `time`
类型。 至少默认值是 `0Nt`:

https://github.com/itfin/Tx/blob/ef0c7792a565146978d58d9a0e1dfd5a8b24c0a1/feed/backtest/ftbacktest.q#L9-L10

`ftbt` 中的 `.z.wc` 查询会触发这个 type error .

也许可以这样：

```
wlog:{[x;y;z]if[(`int$`.enum.loglevels$x)>`int$`.enum.loglevels$.conf.loglevel;:()];z:$[10h=type z;z;-3!z];.db.LOG,:(x;y;z;$[null n:now[];0Np;`timestamp$n]);pub[`syslog;enlist `sym`typ`msg!(x;y;z)];};
```

用 
```
$[null n:now[];0Np;`timestamp$n]
```

 代替 `now[]`.

**Comment by itfin** [comment]
now[] in ftbacktest.q 应当返回timestamp类型，已修复.
